### ISSUE TITLE
Why are you installing chocolatery and adding a wallpaper?

### ISSUE THREAD

**Issue by barruka** [Deen0X/DNXDOScript#1]
Why are you installing chocolatery and adding a wallpaper?

**Comment by Deen0X** [comment]
Hi!
I think Chocolatery was a good idea to add, but you can edit the script, moving the "Z90_Install Chocolatey Repository.cmd" from "Enabled" to "Disabled" folder.
I Set the wallpaper as a way to know that the script run on the machine.
you can change the wallpaper replacing this:
".\Extras\Wallpaper.jpg"

the main reason i set the wallpaper is because i set many machines at the same time, and run the script on all of them... and many times i forgot what i did, so the wallpaper indicates that the process finished on this machine.

There is no other reason for changing this.

if you don´t want to change the wallpaper, simply delete the "".\Extras\Wallpaper.jpg" file

in any case, i will consider on create a subscript for the wallpaper, and enable/disable this easy, similar to the rest of the subscripts (moving from enable/disable folder)

Greetings!
